#!/usr/bin/env bash

# Submit a large 4-GPU grouped rollout collection job for the current
# seed-search GRPO task set. This is a thin qsub wrapper around
# jobs/myriad/30_collect_grouped_rollouts_4gpu.sh.

set -euo pipefail

REPO_ROOT="${REPO_ROOT:-"$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"}"
cd "${REPO_ROOT}"

JOB_SCRIPT="${JOB_SCRIPT:-jobs/myriad/30_collect_grouped_rollouts_4gpu.sh}"
JOB_NAME="${JOB_NAME:-wam_grpo_s8}"
NUM_GPUS="${NUM_GPUS:-4}"
GROUP_SIZE="${GROUP_SIZE:-4}"
GROUPS_PER_TASK="${GROUPS_PER_TASK:-8}"
START_SEED="${START_SEED:-60000}"
PROMPT_INDEX="${PROMPT_INDEX:-0}"
GROUP_SEED_SEARCH="${GROUP_SEED_SEARCH:-true}"
GROUP_SEED_SEARCH_MAX_ATTEMPTS="${GROUP_SEED_SEARCH_MAX_ATTEMPTS:-100}"
GROUP_RETRY_MULTIPLIER="${GROUP_RETRY_MULTIPLIER:-4}"
GROUP_MAX_ATTEMPTS="${GROUP_MAX_ATTEMPTS:-$((GROUPS_PER_TASK * GROUP_RETRY_MULTIPLIER))}"
STRICT_GRPO_CAPTURE="${STRICT_GRPO_CAPTURE:-true}"
STRICT_GRPO_TRANSITION_STD="${STRICT_GRPO_TRANSITION_STD:-0.01}"
STRICT_GRPO_CAPTURE_SCOPE="${STRICT_GRPO_CAPTURE_SCOPE:-action_denoising_trajectory}"
STRICT_GRPO_SAVE_REPLAY_CONTEXT="${STRICT_GRPO_SAVE_REPLAY_CONTEXT:-false}"
ACTION_NUM_INFERENCE_STEPS="${ACTION_NUM_INFERENCE_STEPS:-50}"
TASK_NAMES="${TASK_NAMES:-hanging_mug open_microwave turn_switch move_stapler_pad place_mouse_pad adjust_bottle pick_dual_bottles click_bell}"
RUN_ID="${RUN_ID:-grpo_scale_8tasks_k${GROUP_SIZE}_g${GROUPS_PER_TASK}_seedsearch_$(date +%Y%m%d_%H%M%S)}"
USE_EXISTING_RESULTS_ROOT="${USE_EXISTING_RESULTS_ROOT:-0}"
USE_EXISTING_STABLE_SEED_CACHE_DIR="${USE_EXISTING_STABLE_SEED_CACHE_DIR:-0}"

if ! command -v qsub >/dev/null 2>&1; then
    echo "qsub is not available on PATH. Run this on a Myriad login node." >&2
    exit 2
fi

if [ ! -f "${JOB_SCRIPT}" ]; then
    echo "Missing job script: ${JOB_SCRIPT}" >&2
    exit 2
fi

read -r -a TASK_ARRAY <<< "${TASK_NAMES}"
TASK_COUNT="${#TASK_ARRAY[@]}"
if [ "${TASK_COUNT}" -eq 0 ]; then
    echo "TASK_NAMES is empty." >&2
    exit 2
fi

BATCHES_PER_SAMPLE=$(((TASK_COUNT + NUM_GPUS - 1) / NUM_GPUS))
TOTAL_ROLLOUTS=$((TASK_COUNT * GROUPS_PER_TASK * GROUP_SIZE))
TOTAL_CLIENT_BATCHES=$((GROUPS_PER_TASK * GROUP_SIZE * BATCHES_PER_SAMPLE))

mkdir -p logs/jobs

export REPO_ROOT
export NUM_GPUS
export GROUP_SIZE
export GROUPS_PER_TASK
export START_SEED
export PROMPT_INDEX
export GROUP_SEED_SEARCH
export GROUP_SEED_SEARCH_MAX_ATTEMPTS
export GROUP_RETRY_MULTIPLIER
export GROUP_MAX_ATTEMPTS
export STRICT_GRPO_CAPTURE
export STRICT_GRPO_TRANSITION_STD
export STRICT_GRPO_CAPTURE_SCOPE
export STRICT_GRPO_SAVE_REPLAY_CONTEXT
export ACTION_NUM_INFERENCE_STEPS
export TASK_NAMES
export RUN_ID

if [ "${USE_EXISTING_RESULTS_ROOT}" = "1" ] && [ -n "${RESULTS_ROOT:-}" ]; then
    export RESULTS_ROOT
else
    unset RESULTS_ROOT
fi

if [ "${USE_EXISTING_STABLE_SEED_CACHE_DIR}" = "1" ] && [ -n "${STABLE_SEED_CACHE_DIR:-}" ]; then
    export STABLE_SEED_CACHE_DIR
else
    unset STABLE_SEED_CACHE_DIR
fi

cat <<EOF
Submitting grouped rollout scale job
  JOB_NAME=${JOB_NAME}
  RUN_ID=${RUN_ID}
  REPO_ROOT=${REPO_ROOT}
  TASK_COUNT=${TASK_COUNT}
  TASK_NAMES=${TASK_NAMES}
  NUM_GPUS=${NUM_GPUS}
  GROUP_SIZE=${GROUP_SIZE}
  GROUPS_PER_TASK=${GROUPS_PER_TASK}
  START_SEED=${START_SEED}
  GROUP_SEED_SEARCH=${GROUP_SEED_SEARCH}
  GROUP_SEED_SEARCH_MAX_ATTEMPTS=${GROUP_SEED_SEARCH_MAX_ATTEMPTS}
  GROUP_MAX_ATTEMPTS=${GROUP_MAX_ATTEMPTS}
  STRICT_GRPO_CAPTURE_SCOPE=${STRICT_GRPO_CAPTURE_SCOPE}
  STRICT_GRPO_SAVE_REPLAY_CONTEXT=${STRICT_GRPO_SAVE_REPLAY_CONTEXT}
  TOTAL_ROLLOUTS=${TOTAL_ROLLOUTS}
  TOTAL_CLIENT_BATCHES=${TOTAL_CLIENT_BATCHES}
  USE_EXISTING_RESULTS_ROOT=${USE_EXISTING_RESULTS_ROOT}
EOF

qsub -V -N "${JOB_NAME}" "${JOB_SCRIPT}"
