#!/usr/bin/env bash

# Submit a storage-bounded replay-context grouped rollout collection.
# This is a conservative wrapper around 32_submit_grpo_scale_8tasks_4gpu.sh
# for actor-replay data collection, not a benchmark-scale rollout launcher.

set -euo pipefail

REPO_ROOT="${REPO_ROOT:-"$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"}"
cd "${REPO_ROOT}"

SUBMIT_SCRIPT="${SUBMIT_SCRIPT:-jobs/myriad/32_submit_grpo_scale_8tasks_4gpu.sh}"
DRY_RUN="${DRY_RUN:-0}"

JOB_NAME="${JOB_NAME:-wam_grpo_replayctx_bounded}"
TASK_NAMES="${TASK_NAMES:-move_stapler_pad}"
GROUP_SIZE="${GROUP_SIZE:-8}"
GROUPS_PER_TASK="${GROUPS_PER_TASK:-1}"
START_SEED="${START_SEED:-99200}"
PROMPT_INDEX="${PROMPT_INDEX:-0}"
ACTION_NUM_INFERENCE_STEPS="${ACTION_NUM_INFERENCE_STEPS:-10}"
GROUP_SEED_SEARCH_MAX_ATTEMPTS="${GROUP_SEED_SEARCH_MAX_ATTEMPTS:-120}"
GROUP_RETRY_MULTIPLIER="${GROUP_RETRY_MULTIPLIER:-12}"
GROUP_MAX_ATTEMPTS="${GROUP_MAX_ATTEMPTS:-$((GROUPS_PER_TASK * GROUP_RETRY_MULTIPLIER))}"
STRICT_GRPO_CAPTURE="${STRICT_GRPO_CAPTURE:-true}"
STRICT_GRPO_TRANSITION_STD="${STRICT_GRPO_TRANSITION_STD:-0.01}"
STRICT_GRPO_CAPTURE_SCOPE="${STRICT_GRPO_CAPTURE_SCOPE:-action_denoising_trajectory}"
STRICT_GRPO_SAVE_REPLAY_CONTEXT="${STRICT_GRPO_SAVE_REPLAY_CONTEXT:-true}"
STRICT_GRPO_CAPTURE_CHUNK_STRIDE="${STRICT_GRPO_CAPTURE_CHUNK_STRIDE:-1}"
STRICT_GRPO_CAPTURE_MAX_CHUNKS="${STRICT_GRPO_CAPTURE_MAX_CHUNKS:-1}"
SAVE_SERVER_DEBUG_TENSORS="${SAVE_SERVER_DEBUG_TENSORS:-false}"
RUN_ID="${RUN_ID:-grpo_replayctx_bounded_k${GROUP_SIZE}_g${GROUPS_PER_TASK}_s${ACTION_NUM_INFERENCE_STEPS}_$(date +%Y%m%d_%H%M%S)}"

if [ ! -f "${SUBMIT_SCRIPT}" ]; then
    echo "Missing submit script: ${SUBMIT_SCRIPT}" >&2
    exit 2
fi

cat <<EOF
Bounded replay-context GRPO collection
  JOB_NAME=${JOB_NAME}
  RUN_ID=${RUN_ID}
  TASK_NAMES=${TASK_NAMES}
  GROUP_SIZE=${GROUP_SIZE}
  GROUPS_PER_TASK=${GROUPS_PER_TASK}
  START_SEED=${START_SEED}
  PROMPT_INDEX=${PROMPT_INDEX}
  ACTION_NUM_INFERENCE_STEPS=${ACTION_NUM_INFERENCE_STEPS}
  STRICT_GRPO_CAPTURE_SCOPE=${STRICT_GRPO_CAPTURE_SCOPE}
  STRICT_GRPO_SAVE_REPLAY_CONTEXT=${STRICT_GRPO_SAVE_REPLAY_CONTEXT}
  STRICT_GRPO_CAPTURE_CHUNK_STRIDE=${STRICT_GRPO_CAPTURE_CHUNK_STRIDE}
  STRICT_GRPO_CAPTURE_MAX_CHUNKS=${STRICT_GRPO_CAPTURE_MAX_CHUNKS}
  SAVE_SERVER_DEBUG_TENSORS=${SAVE_SERVER_DEBUG_TENSORS}
  GROUP_MAX_ATTEMPTS=${GROUP_MAX_ATTEMPTS}
  DRY_RUN=${DRY_RUN}
EOF

if [ "${DRY_RUN}" = "1" ]; then
    echo "DRY_RUN=1, not submitting ${JOB_NAME}."
    exit 0
fi

JOB_NAME="${JOB_NAME}" \
RUN_ID="${RUN_ID}" \
TASK_NAMES="${TASK_NAMES}" \
GROUP_SIZE="${GROUP_SIZE}" \
GROUPS_PER_TASK="${GROUPS_PER_TASK}" \
START_SEED="${START_SEED}" \
PROMPT_INDEX="${PROMPT_INDEX}" \
ACTION_NUM_INFERENCE_STEPS="${ACTION_NUM_INFERENCE_STEPS}" \
GROUP_SEED_SEARCH=true \
GROUP_SEED_SEARCH_MAX_ATTEMPTS="${GROUP_SEED_SEARCH_MAX_ATTEMPTS}" \
GROUP_RETRY_MULTIPLIER="${GROUP_RETRY_MULTIPLIER}" \
GROUP_MAX_ATTEMPTS="${GROUP_MAX_ATTEMPTS}" \
STRICT_GRPO_CAPTURE="${STRICT_GRPO_CAPTURE}" \
STRICT_GRPO_TRANSITION_STD="${STRICT_GRPO_TRANSITION_STD}" \
STRICT_GRPO_CAPTURE_SCOPE="${STRICT_GRPO_CAPTURE_SCOPE}" \
STRICT_GRPO_SAVE_REPLAY_CONTEXT="${STRICT_GRPO_SAVE_REPLAY_CONTEXT}" \
STRICT_GRPO_CAPTURE_CHUNK_STRIDE="${STRICT_GRPO_CAPTURE_CHUNK_STRIDE}" \
STRICT_GRPO_CAPTURE_MAX_CHUNKS="${STRICT_GRPO_CAPTURE_MAX_CHUNKS}" \
SAVE_SERVER_DEBUG_TENSORS="${SAVE_SERVER_DEBUG_TENSORS}" \
REPO_ROOT="${REPO_ROOT}" \
bash "${SUBMIT_SCRIPT}"
